#!/usr/bin/env bash

## Run site tests.
##
## Usage: fin test

run_tests ()
{
  # We stop and restart the project to start the test run with full memory.
  fin project stop
  fin project start

  # These are mostly split up because of high memory usage.
  echo "Executing Behat JS tests..."
  fin behat --tags=javascript
  js_exit_code=$?

  echo "Executing Behat non-JS tests..."
  fin behat --tags=~javascript
  non_js_exit_code=$?

  # We stop and restart the project to start the test run with full memory.
  fin project stop
  fin project start

  echo "Executing PHPUnit tests..."
  fin phpunit web/modules/custom
  php_unit_exit_code=$?
  echo "Exit $((h5p_exit_code + js_exit_code + non_js_exit_code + php_unit_exit_code))"
  exit $((h5p_exit_code + js_exit_code + non_js_exit_code + php_unit_exit_code))
}

run_tests

